### PR TITLE
alternate fix for #11

### PR DESCRIPTION
**Pull request by luckman212**
Updated version of https://github.com/JonasDoesThings/obsidian-hide-folders/pull/14

Switches to File Explorer at startup so that the DOM elements are available to be hidden.

### CODE REVIEW

**Comment by luckman212** [comment]
@JonasDoesThings Not sure if it's better to natively call the `file-explorer:open` command directly from the internal File Explorer plugin, e.g

```ts
this.app.commands.executeCommandById('file-explorer:open');
```

image

**Comment by JonasDoesThings** [comment]
Hmm, so I understand it correctly; this just opens the "file explorer" tab on every startup instead of restoring the latest opened tab, right? 

I'm wondering if there's a more user-friendly way that doesn't override their tab

**Comment by JonasDoesThings** [comment]
Switching the tab from something else to the file explorer triggers the following mutation-observer:
```
// used for re-processing folders when a folder is expanded in the file-navigator
    this.mutationObserver = new MutationObserver((mutationRecord) => {
      mutationRecord.forEach(record => {
        if(record.target?.parentElement?.classList.contains("nav-folder")) {
          this.processFolders();
          return;
        }

[...]
```

So maybe instead of calling `this.processFolders()` once here, we could also call it twice - once instantly and the second time with a `setTimeout` like on startup. Would this also fix your problem?

**Comment by luckman212** [comment]
@JonasDoesThings Thanks for looking. Not sure I follow, you're saying that there's a callback or something when switching to the FileExplorer?

**Comment by luckman212** [comment]
@JonasDoesThings I played around and got it working, thanks for the tip. Please check #16 and let me know if that's OK for you.

**Pull request closed without merging**
